#! /bin/bash -e

temp_manifest_name=/tmp/manifest.yaml
helm_options=()
datree_options=()
helm_chart=""

while [[ $1 ]]; do
    case "$1" in
    version | help | config)
        $HELM_PLUGIN_DIR/bin/datree $@
        exit
        ;;
    test)
        helm_chart="$2"
        shift 2
        ;;
    --)
        datree_options+=("$2")
        shift 2
        ;;
    *)
        helm_options+=("$1")
        shift
        ;;
    esac
done

helm template "datree_autogenerated_manifest" "$helm_chart" "${helm_options[@]}" >${temp_manifest_name}

$HELM_PLUGIN_DIR/bin/datree test "$temp_manifest_name" "${datree_options[@]}"
